AUTHOR = "Sony Group Corporation"
HOMEPAGE = "https://github.com/sony/flutter-embedded-linux"
BUGTRACKER = "https://github.com/sony/flutter-embedded-linux/issues"

LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://LICENSE;md5=d45359c88eb146940e4bede4f08c821a"

SRC_URI = "git://github.com/sony/flutter-embedded-linux.git;protocol=https;branch=master"
SRCREV = "ee731f304f4e1a3322da048dae5b38baae0d4612"
S = "${WORKDIR}/git"
