AUTHOR = "Sony Group Corporation"
HOMEPAGE = "https://github.com/sony/flutter-embedded-linux"
BUGTRACKER = "https://github.com/sony/flutter-embedded-linux/issues"

LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://LICENSE;md5=d45359c88eb146940e4bede4f08c821a"

SRC_URI = "git://github.com/sony/flutter-embedded-linux.git;protocol=https;branch=master"
SRCREV = "311e9f189a55971c997916c13df49d5e46df4d26"
S = "${WORKDIR}/git"
